### ISSUE TITLE
possible upgrade needed - ansi-html

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/grinnode-live-frontend#45]
CVE-2021-23424
high severity
Vulnerable versions: <= 0.0.7

Patched version: No fix

This affects all versions of package ansi-html. If an attacker provides a malicious string, it will get stuck processing the input for an extremely long time.

Do we use this and do we have a workaround?

**Comment by stakervali** [comment]
Yes we are using it but It is a  development dependency  (used in development web server). It is not included in production code.

![resim](https://user-images.githubusercontent.com/60194710/132573493-cbde8a22-a025-4a44-863c-61990ebbb001.png)
![resim](https://user-images.githubusercontent.com/60194710/132573531-f013dfd4-c141-4f41-ae5c-58ea0055cf4f.png)

**Comment by MCM-Mike** [comment]
could you update it also on de development branch so we can close this issue?

**Comment by stakervali** [comment]
I have not describe clearly. Every vue project comes with development web server so that we don't need to do a `npm run build` step during development. It hot reloads every change. When we build the app,  web-dev-server files are excluded and not distributed to client. So there is no need for action and we can close it.

**Comment by MCM-Mike** [comment]
thank you for the explanation. I will close this issues
